### PR TITLE
fix dependency on sweet_xml when not required, and handle s3_multipar…

### LINKED ISSUE #81: SweetXML as hard dependency on 0.4.10?
Hi Ben,

just updated `ex_aws` dependency on my project from 0.4.8 to 0.4.10 and now get this error on compilation:
```
== Compilation error on file lib/ex_aws/s3/parsers.ex ==
** (CompileError) lib/ex_aws/s3/parsers.ex:3: module SweetXml is not loaded and could not be found
    (elixir) expanding macro: Kernel.if/2
    lib/ex_aws/s3/parsers.ex:2: ExAws.S3.Parsers (module)
    (elixir) lib/kernel/parallel_compiler.ex:97: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8

could not compile dependency ex_aws, mix compile failed. You can recompile this dependency with `mix deps.compile ex_aws` or update it with `mix deps.update ex_aws
```

Has SweetXML become a mandatory dependency?

Thanks!

### LINKED ISSUE #91: ExAws.S3.Impl.list_multipart_uploads is broken
```
    params = @params |> format_and_take(opts)
```

must be 

```
    params = opts |> format_and_take(@params)
```

### PR DESCRIPTION
**Pull request by benwilson512**
Fixes #91
Fixes #81

### CODE REVIEW

File: lib/ex_aws/s3/parsers.ex [hunk 1]
```diff
@@ -1,5 +1,5 @@
-defmodule ExAws.S3.Parsers do
-  if Code.ensure_loaded?(SweetXml) do
+if Code.ensure_loaded?(SweetXml) do
+  defmodule ExAws.S3.Parsers do
```
Comment (ericmj) [inline lib/ex_aws/s3/parsers.ex]: :+1:
